version: "3.9"
services:
  app:
    build:
      context: .
      args:
        DEPLOY_API: localhost:5001
        DEPLOY_CDN: localhost:5001
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./MyApp/App_Data:/app/App_Data
      - ~/.aspnet/https:/https:ro
  app-migration:
    build: .
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - ./MyApp/App_Data:/app/App_Data