version: "3.9"
services:
  app:
    build:
      context: .
      args:
        DEPLOY_API: localhost:5000
        DEPLOY_CDN: localhost:5000
    ports:
      - "5000:80"
    volumes:
      - app-mydb:/app/App_Data
  app-migration:
    build: .
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - app-mydb:/app/App_Data

volumes:
  app-mydb: