name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test ./MyApp.Tests
